### ISSUE TITLE
Config output path is relative to input path

### ISSUE THREAD

**Issue by elliotsimon** [e-WindLidar/Lidaco#6]
Output path inside config.yaml should be relative to the starting path, not to the folder containing data.

Currently:

   input:
    path: "./20170409113034_PPI1/"
    format: Windscanner

  output: 
    path: "../output/"
    format: NetCDF4

Proposed:

   input:
    path: "./20170409113034_PPI1/"
    format: Windscanner

  output: 
    path: "./output/"
    format: NetCDF4

**Comment by danfergo** [comment]
Hi Elliot, 
I believe this bug is fixed additionally, I set the core to assume "./output/" in case of no output path being specified. Update to the latest version of Lidaco. If you keep having troubles with these feel free to reopen the issue. Thanks.

EDIT: I've also improved the README file parameters section. I think the stuff you were talking about in the workshop gets clear with these additions.
